title: Anatoly Nikiforov - Technical Portfolio
description: Architecture, Algorithms, System Design
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - about/
  - specs/
  - deep-dives/
