title: Anatoly Nikiforov
description: Architecture, Algorithms, System Design
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - about/
  - specs/
  - deep-dives/
  
highlighter: rouge
rouge_theme: monokai # Or 'base16.solarized.dark'